/*
 * Tikkie Payment Integration APIs
 * This is an integration APIs with Tikkie Payment gateway
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tikkiepayment.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GetPaymentListSuccess
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-05T18:33:16.985Z[GMT]")
public class GetPaymentListSuccess {
  @SerializedName("payments")
  private List<Payment> payments = null;

  @SerializedName("totalElementCount")
  private Integer totalElementCount = null;

  public GetPaymentListSuccess payments(List<Payment> payments) {
    this.payments = payments;
    return this;
  }

  public GetPaymentListSuccess addPaymentsItem(Payment paymentsItem) {
    if (this.payments == null) {
      this.payments = new ArrayList<Payment>();
    }
    this.payments.add(paymentsItem);
    return this;
  }

   /**
   * Payments
   * @return payments
  **/
  @Schema(description = "Payments")
  public List<Payment> getPayments() {
    return payments;
  }

  public void setPayments(List<Payment> payments) {
    this.payments = payments;
  }

  public GetPaymentListSuccess totalElementCount(Integer totalElementCount) {
    this.totalElementCount = totalElementCount;
    return this;
  }

   /**
   * Total amount of payments which match the parameters provided.
   * @return totalElementCount
  **/
  @Schema(example = "75", description = "Total amount of payments which match the parameters provided.")
  public Integer getTotalElementCount() {
    return totalElementCount;
  }

  public void setTotalElementCount(Integer totalElementCount) {
    this.totalElementCount = totalElementCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPaymentListSuccess getPaymentListSuccess = (GetPaymentListSuccess) o;
    return Objects.equals(this.payments, getPaymentListSuccess.payments) &&
        Objects.equals(this.totalElementCount, getPaymentListSuccess.totalElementCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payments, totalElementCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPaymentListSuccess {\n");
    
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    totalElementCount: ").append(toIndentedString(totalElementCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
